#!/bin/bash

# Get current date and time
now=$(date +'%A, %B %d, %Y - %H:%M:%S %Z')

# Get disk usage information
df_output=$(df -h /)
total_space=$(echo "$df_output" | awk 'NR==2{print $2}')
remaining_space=$(echo "$df_output" | awk 'NR==2{print $4}')

# Calculate available space percentage
space_pct=$(echo "$df_output" | awk 'NR==2{print $5}')

# Define characters for bar graph (adjust as needed)
full="#"
empty="-"

# Calculate number of full and empty characters for bar
full_chars=$(echo "$space_pct" | cut -d "%" -f1)
empty_chars=$((100 - full_chars))

# Generate bar graph
bar_graph=""
for (( i=0; i<$full_chars; i++ )); do
  bar_graph+="$full"
done
for (( i=0; i<$empty_chars; i++ )); do
  bar_graph+="$empty"
done

# Get internal and external IP addresses
internal_ip=$(hostname -I | awk '{print $1}')
external_ip=$(curl -s https://icanhazip.com)  # Replace with preferred external IP service

#Print MOTD
echo "$(tput setaf 2) 
`date +"%A, %e %B %Y, %r"` 
`uname -srmo`"

echo ""
echo ""



echo "$(tput sgr0) Last login information:"
echo "---------------------------------------------"
printf "%-15s | %-15s | %-20s | %-20s\n" "Username" "Terminal" "Date" "IP Address"
echo "---------------------------------------------"
last | head -n 1 | awk '{printf "%-15s | %-15s | %-20s | %-20s\n", $1, $2, $4" "$5" "$6, $3}'
echo "---------------------------------------------"

echo "
$(tput sgr0)Total Disk Space: $total_space
$(tput sgr0)Remaining Disk Space: $remaining_space/$total_space ($space_pct)
$(tput sgr0)Disk Usage: [$bar_graph]
$(tput sgr0)Internal IP: $internal_ip
$(tput sgr0)External IP: $external_ip
"