#!/bin/bash

export TERM=xterm-256color

clear 

echo "$(tput bold)$(tput setaf 2)"
echo "    .~~.   .~~.  "
echo "   '. \ ' ' / .' "
echo "$(tput setaf 1)"
echo "    .~ .~~~..~.   "
echo "   : .~.'~'.~. :  "  
echo "  ~ (   ) (   ) ~ "  
echo " ( : '~'.~.'~' : )"    
echo "  ~ .~ (   ) ~. ~ "  
echo "   (  : '~' :  )  "  
echo "    '~ .~~~. ~'   "
echo "        '~'      "

#Get Uptime
let upSeconds="$(/usr/bin/cut -d. -f1 /proc/uptime)"
let secs=$((${upSeconds}%60))
let mins=$((${upSeconds}/60%60))
let hours=$((${upSeconds}/3600%24))
let days=$((${upSeconds}/86400))
UPTIME=`printf "%d days, %02dh%02dm%02ds" "$days" "$hours" "$mins" "$secs"`

#Get load averages
read one five fifteen rest < /proc/loadavg

# Get disk usage information
df_output=$(df -h /)
total_space=$(echo "$df_output" | awk 'NR==2{print $2}')
remaining_space=$(echo "$df_output" | awk 'NR==2{print $4}')

# Calculate available space percentage
space_pct=$(echo "$df_output" | awk 'NR==2{print $5}' | cut -d "%" -f1)

# Calculate number of full and empty characters for bar
full_chars=$((($space_pct * 50 + 50/2) / 100))
empty_chars=$((50 - full_chars))

# Generate bar graph
bar_graph=""
for (( i=0; i<full_chars; i++ )); do
  bar_graph+="■"  # Assuming "■" represents a full character
done
for (( i=0; i<empty_chars; i++ )); do
  bar_graph+="-"  # Adding a space for an empty character
done

# Get internal and external IP addresses
internal_ip=$(hostname -I | awk '{print $1}')
external_ip=$(curl -s https://icanhazip.com)

echo "$(tput setaf 2)
`date +"%A, %e %B %Y, %r"`
`uname -srmo`

$(tput setaf 1)
- Uptime.........................: ${UPTIME}
$(tput setaf 2)
- Total Disk Space...............: $total_space
- Remaining Disk Space...........: $remaining_space/$total_space ($space_pct%)
- Disk Usage: [$bar_graph]
$(tput setaf 4)
- Memory.........................: `free | grep Mem | awk '{print $3/1024}'` MB (Used) / `cat /proc/meminfo | grep MemTotal | awk {'print $2/1024'}` MB (Total)
- Load Averages..................: ${one}, ${five}, ${fifteen} (1, 5, 15 min)
- Running Processes..............: `ps ax | wc -l | tr -d " "`
$(tput setaf 5)
- IP Adresses....................: $internal_ip and $external_ip
"